var searchData=
[
  ['hdghypergraph_0',['HDGHyperGraph',['../classHDGHyperGraph.html',1,'']]],
  ['hdghypergraph_3c_20localsolvert_3a_3an_5fglob_5fdofs_5fper_5fnode_28_29_2c_20topologyt_2c_20geometryt_2c_20nodedescriptort_2c_20typename_20localsolvert_3a_3adata_5ftype_20_3e_1',['HDGHyperGraph&lt; LocalSolverT::n_glob_dofs_per_node(), TopologyT, GeometryT, NodeDescriptorT, typename LocalSolverT::data_type &gt;',['../classHDGHyperGraph.html',1,'']]],
  ['helper_5fev_5fapprox_2',['helper_ev_approx',['../classbilaplacian__convergence__eigenvalue__approx_1_1helper__ev__approx.html',1,'bilaplacian_convergence_eigenvalue_approx.helper_ev_approx'],['../classbilaplacian__convergence__eigenvalue__shifted__inverse_1_1helper__ev__approx.html',1,'bilaplacian_convergence_eigenvalue_shifted_inverse.helper_ev_approx'],['../classbilaplacian__hypergraph__convergence__eigenvalue__approx_1_1helper__ev__approx.html',1,'bilaplacian_hypergraph_convergence_eigenvalue_approx.helper_ev_approx'],['../classbilaplacian__hypergraph__convergence__eigenvalue__shifted__inverse_1_1helper__ev__approx.html',1,'bilaplacian_hypergraph_convergence_eigenvalue_shifted_inverse.helper_ev_approx'],['../classdiffusion__convergence__eigenvalue__approx_1_1helper__ev__approx.html',1,'diffusion_convergence_eigenvalue_approx.helper_ev_approx'],['../classdiffusion__convergence__eigenvalue__shifted__inverse_1_1helper__ev__approx.html',1,'diffusion_convergence_eigenvalue_shifted_inverse.helper_ev_approx'],['../classdiffusion__convergence__eigenvalue__shifted__inverse__cross_1_1helper__ev__approx.html',1,'diffusion_convergence_eigenvalue_shifted_inverse_cross.helper_ev_approx'],['../classdiffusion__hypergraph__convergence__eigenvalue__approx_1_1helper__ev__approx.html',1,'diffusion_hypergraph_convergence_eigenvalue_approx.helper_ev_approx'],['../classdiffusion__hypergraph__convergence__eigenvalue__shifted__inverse_1_1helper__ev__approx.html',1,'diffusion_hypergraph_convergence_eigenvalue_shifted_inverse.helper_ev_approx']]],
  ['helper_5fev_5fnewt_3',['helper_ev_newt',['../classbilaplacian__convergence__eigenvalue__newt_1_1helper__ev__newt.html',1,'bilaplacian_convergence_eigenvalue_newt.helper_ev_newt'],['../classbilaplacian__hypergraph__convergence__eigenvalue__newt_1_1helper__ev__newt.html',1,'bilaplacian_hypergraph_convergence_eigenvalue_newt.helper_ev_newt'],['../classdiffusion__convergence__eigenvalue__newt_1_1helper__ev__newt.html',1,'diffusion_convergence_eigenvalue_newt.helper_ev_newt'],['../classdiffusion__hypergraph__convergence__eigenvalue__newt_1_1helper__ev__newt.html',1,'diffusion_hypergraph_convergence_eigenvalue_newt.helper_ev_newt'],['../classdiffusion__hypergraph__convergence__eigenvalue__newt__cross_1_1helper__ev__newt.html',1,'diffusion_hypergraph_convergence_eigenvalue_newt_cross.helper_ev_newt']]],
  ['hg_4',['HG',['../structHG.html',1,'']]],
  ['hydatacontainer_5',['HyDataContainer',['../classHyDataContainer.html',1,'']]],
  ['hydatacontainer_3c_20emptyc_20_3e_6',['HyDataContainer&lt; EmptyC &gt;',['../classHyDataContainer.html',1,'']]],
  ['hydatacontainer_3c_20typename_20localsolvert_3a_3adata_5ftype_20_3e_7',['HyDataContainer&lt; typename LocalSolverT::data_type &gt;',['../classHyDataContainer.html',1,'']]],
  ['hyedge_8',['hyedge',['../classGeometry_1_1File_1_1hyEdge.html',1,'Geometry::File&lt; hyEdge_dimT, space_dimT, vectorT, pointT, mapping_tM, hyEdge_dimTM, space_dimTM, pt_coord_tM, hyEdge_index_t, hyNode_index_t, pt_index_t &gt;::hyEdge'],['../classGeometry_1_1UnitCube_1_1hyEdge.html',1,'Geometry::UnitCube&lt; hyEdge_dimT, space_dimT, pt_coord_t, ConstructorVecT, hyEdge_index_t &gt;::hyEdge'],['../structHDGHyperGraph_1_1hyEdge.html',1,'HDGHyperGraph&lt; n_dofs_per_nodeT, TopoT, GeomT, NodeT, DataT, hyEdge_index_t &gt;::hyEdge'],['../classNodeDescriptor_1_1Cubic_1_1hyEdge.html',1,'NodeDescriptor::Cubic&lt; hyEdge_dimT, space_dimT, NodeTypeVecT, ConstructorVecT, hyEdge_index_t, hyNode_index_t &gt;::hyEdge'],['../classNodeDescriptor_1_1File_1_1hyEdge.html',1,'NodeDescriptor::File&lt; hyEdge_dimT, space_dimT, vectorT, pointT, hyEdge_index_t, hyNode_index_t, pt_index_t &gt;::hyEdge'],['../classTopology_1_1Cubic_1_1hyEdge.html',1,'Topology::Cubic&lt; hyEdge_dimT, space_dimT, NodeIndexVecT, ConstructorVecT, hyEdge_index_t, NodeOrientationT &gt;::hyEdge'],['../classTopology_1_1File_1_1hyEdge.html',1,'Topology::File&lt; hyEdge_dimT, space_dimT, vectorT, pointT, hyEdge_index_t, hyNode_index_t, pt_index_t, NodeOrientationT &gt;::hyEdge']]],
  ['hypercube_9',['hypercube',['../structHypercube.html',1,'Hypercube&lt; dimT &gt;'],['../structTPP_1_1Hypercube.html',1,'TPP::Hypercube&lt; dimT &gt;']]],
  ['hypergraphmovie_10',['HyperGraphMovie',['../structHyperGraphMovie.html',1,'']]],
  ['hypernodefactory_11',['HyperNodeFactory',['../classHyperNodeFactory.html',1,'']]],
  ['hypernodefactory_3c_20n_5fdofs_5fper_5fnodet_2c_20unsigned_20int_20_3e_12',['HyperNodeFactory&lt; n_dofs_per_nodeT, unsigned int &gt;',['../classHyperNodeFactory.html',1,'']]]
];
